import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import * as archiver from 'archiver';
import { Readable } from 'stream';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class ExportService {
  constructor(private prisma: PrismaService) {}

  async generateExport(project: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const archive = archiver('zip', {
        zlib: { level: 9 },
      });

      const chunks: Buffer[] = [];
      const stream = new Readable({
        read() {},
      });

      archive.on('data', (data: Buffer) => {
        chunks.push(data);
      });

      archive.on('end', () => {
        resolve(Buffer.concat(chunks));
      });

      archive.on('error', (err: Error) => {
        reject(err);
      });

      // Generate README
      const readme = this.generateReadme(project);
      archive.append(readme, { name: 'README.md' });

      // Generate project structure
      const projectJson = this.generateProjectJson(project);
      archive.append(projectJson, { name: 'project.json' });

      // Add requirements
      if (project.requirements && project.requirements.length > 0) {
        const reqsMarkdown = this.generateRequirementsMarkdown(project.requirements);
        archive.append(reqsMarkdown, { name: 'REQUIREMENTS.md' });
      }

      // Add features
      if (project.features && project.features.length > 0) {
        const featuresMarkdown = this.generateFeaturesMarkdown(project.features);
        archive.append(featuresMarkdown, { name: 'FEATURES.md' });
      }

      // Add architecture
      if (project.architecture) {
        const archMarkdown = this.generateArchitectureMarkdown(project.architecture);
        archive.append(archMarkdown, { name: 'ARCHITECTURE.md' });
      }

      // Add code blocks
      if (project.codeBlocks && project.codeBlocks.length > 0) {
        archive.append(this.generateCodeMarkdown(project.codeBlocks), {
          name: 'CODE_BLOCKS.md',
        });
      }

      archive.finalize();
    });
  }

  private generateReadme(project: any): string {
    const techStack = {
      languages: project.detectedLanguages ? JSON.parse(project.detectedLanguages) : [],
      frameworks: project.detectedFrameworks ? JSON.parse(project.detectedFrameworks) : [],
      databases: project.detectedDatabases ? JSON.parse(project.detectedDatabases) : [],
    };

    return `# ${project.name}

${project.description || 'No description provided'}

## Project Metadata

- **Created**: ${new Date(project.createdAt).toISOString()}
- **Last Updated**: ${new Date(project.updatedAt).toISOString()}
- **Status**: ${project.status}

## Technology Stack

### Languages
${techStack.languages.map((l: string) => `- ${l}`).join('\n') || '- Not detected'}

### Frameworks
${techStack.frameworks.map((f: string) => `- ${f}`).join('\n') || '- Not detected'}

### Databases
${techStack.databases.map((d: string) => `- ${d}`).join('\n') || '- Not detected'}

## Contents

- [Requirements](./REQUIREMENTS.md)
- [Features](./FEATURES.md)
- [Architecture](./ARCHITECTURE.md)
- [Code Blocks](./CODE_BLOCKS.md)
- [Project Data](./project.json)

---

*Generated by AI Project Compiler*
`;
  }

  private generateRequirementsMarkdown(requirements: any[]): string {
    let md = '# Requirements\n\n';

    for (const req of requirements) {
      md += `## ${req.title}\n`;
      md += `\n**Status**: ${req.status}\n`;
      md += `**Priority**: ${req.priority}\n\n`;
      md += `${req.description}\n\n`;
    }

    return md;
  }

  private generateFeaturesMarkdown(features: any[]): string {
    let md = '# Features\n\n';

    for (const feature of features) {
      md += `## ${feature.name}\n`;
      md += `\n**Status**: ${feature.status}\n`;
      md += `**Priority**: ${feature.priority}\n\n`;
      md += `${feature.description}\n\n`;

      if (feature.tasks && feature.tasks.length > 0) {
        md += '### Tasks\n';
        for (const task of feature.tasks) {
          md += `- [ ] ${task.title}\n`;
        }
        md += '\n';
      }
    }

    return md;
  }

  private generateArchitectureMarkdown(architecture: any): string {
    return `# Architecture\n\n## Overview\n\n${architecture.overview || 'Not specified'}\n\n## Components\n\n${architecture.components || 'Not specified'}\n\n## Layers\n\n${architecture.layers || 'Not specified'}\n`;
  }

  private generateCodeMarkdown(codeBlocks: any[]): string {
    let md = '# Code Blocks\n\n';

    for (const block of codeBlocks) {
      md += `## ${block.language || 'Code'}\n\n`;
      if (block.description) {
        md += `${block.description}\n\n`;
      }
      md += `\`\`\`${block.language}\n${block.content}\n\`\`\`\n\n`;
    }

    return md;
  }

  private generateProjectJson(project: any): string {
    const json = {
      id: project.id,
      name: project.name,
      description: project.description,
      status: project.status,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
      techStack: {
        languages: project.detectedLanguages
          ? JSON.parse(project.detectedLanguages)
          : [],
        frameworks: project.detectedFrameworks
          ? JSON.parse(project.detectedFrameworks)
          : [],
        databases: project.detectedDatabases
          ? JSON.parse(project.detectedDatabases)
          : [],
      },
      stats: {
        requirements: project.requirements?.length || 0,
        features: project.features?.length || 0,
        tasks: project.tasks?.length || 0,
        codeBlocks: project.codeBlocks?.length || 0,
      },
    };

    return JSON.stringify(json, null, 2);
  }
}
